# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Set Proxy (proxyconf plugin needed)
  # > $ vagrant plugin install vagrant-proxyconf
  #config.proxy.http     = "http://USR:PW@SERVER:PORT/"
  #config.proxy.https    = "http://USR:PW@SERVER:PORT/"
  #config.proxy.no_proxy = "localhost,127.0.0.1"

  # box base image
  config.vm.box = "ubuntu/trusty64"

  # shared folder between host (param01) and guest (param02)
  #config.vm.synced_folder "./guestData/", "/vagrant_data"

  # virtualbox specific configuration
  config.vm.provider "virtualbox" do |vb|
    # customize available memory
    vb.memory = "2048"
  end

  # https://www.vagrantup.com/docs/multi-machine/
  config.vm.define "hadoop_master" do |hdp|
    # config ssh connections
    hdp.ssh.insert_key = false

    # remap host port to guest port
    hdp.vm.network "forwarded_port", guest: 50070, host: 50070

    # enable provisioning via puppet
    hdp.vm.provision :puppet do |puppet|
      puppet.manifests_path = "puppet/manifests"
      puppet.manifest_file = "hadoop-machine.pp"
      puppet.module_path = "puppet/modules"
    end
  end

  config.vm.define "kafka_node" do |kfk|
    # enable provisioning via puppet
    kfk.vm.provision :puppet do |puppet|
      puppet.manifests_path = "puppet/manifests"
      puppet.manifest_file = "hadoop-machine.pp"
      puppet.module_path = "puppet/modules"
    end
  end


=begin
  config.vm.define "cassandra_seed" do |css|
    # ...
  end
=end
end
