# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Set Proxy (proxyconf plugin needed)
  # > $ vagrant plugin install vagrant-proxyconf
  #config.proxy.http     = "http://USR:PW@SERVER:PORT/"
  #config.proxy.https    = "http://USR:PW@SERVER:PORT/"
  #config.proxy.no_proxy = "localhost,127.0.0.1"

  # box base image
  config.vm.box = "ubuntu/trusty64"

  # shared folder between host (param01) and guest (param02)
  #config.vm.synced_folder "./guestData/", "/vagrant_data"

  # virtualbox specific configuration
  config.vm.provider "virtualbox" do |vb|
    # customize available memory
    vb.memory = "2048"
  end

  # config ssh connections
  config.ssh.insert_key = false

  # https://www.vagrantup.com/docs/multi-machine/
  config.vm.define "hadoop_master" do |hdp|
    hdp.vm.hostname = "hadoopmaster"
    # assign "local" ip
    hdp.vm.network "private_network", ip: "10.10.33.11"
    # remap host port to guest port
    hdp.vm.network "forwarded_port", guest: 50070, host: 50070  # web ui namenode
    hdp.vm.network "forwarded_port", guest: 50030, host: 50030  # web ui jobtracker
    hdp.vm.network "forwarded_port", guest: 9000, host: 9000    # (hd)fs

    # enable provisioning via puppet
    hdp.vm.provision :puppet do |puppet|
      puppet.manifests_path = "puppet/manifests"
      puppet.manifest_file = "hadoop-machine.pp"
      puppet.module_path = "puppet/modules"
    end
  end

  config.vm.define "kafka_node" do |kfk|
    kfk.vm.hostname = "kafkanode"
    kfk.vm.network "private_network", ip: "10.10.33.22"
    kfk.vm.network "forwarded_port", guest: 2181, host: 2181
    kfk.vm.network "forwarded_port", guest: 9092, host: 9092

    kfk.vm.provision :puppet do |puppet|
      puppet.manifests_path = "puppet/manifests"
      puppet.manifest_file = "kafka-machine.pp"
      puppet.module_path = "puppet/modules"
    end
  end

  config.vm.define "cassandra_seed" do |css|
    css.vm.hostname = "cassandraseed"
    css.vm.network "private_network", ip: "10.10.33.33"
    css.vm.network "forwarded_port", guest: 7000, host: 7000
    css.vm.network "forwarded_port", guest: 7001, host: 7001

    css.vm.provision :puppet do |puppet|
      puppet.manifests_path = "puppet/manifests"
      puppet.manifest_file = "cassandra-machine.pp"
      puppet.module_path = "puppet/modules"
    end
  end

end
